version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: dotnet_payments_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 10s
      timeout: 5s
      retries: 5

  paymentsapi:
    image: paymentsapi:latest
    container_name: dotnet_payments_api
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - payment_data:/app/payment-data
    ports:
      - "8090:8090"
      - "8091:8091"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8090
      - RabbitMQ__Host=rabbitmq
      - AWS__ServiceUrl=http://host.docker.internal:4566
      - PaymentDelivery__Directory=/app/payment-data
    depends_on:
      rabbitmq:
        condition: service_healthy

volumes:
  payment_data:
  rabbitmq_data:

